language: android
jdk: oraclejdk8
sudo: false

notifications:
    email:
        - kevalpatel2106@gmail.com
        
env:
    matrix:
        #- ANDROID_TARGET=android-24 ANDROID_ABI=armeabi-v7a
        - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a
    global:
        - ADB_INSTALL_TIMEOUT=10    #Time out to 10 mins
    
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:      #Cache all dirs under .gradle folder
    - $HOME/.gradle/daemon      #Cache daemon logs
    - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
    - $HOME/.gradle/wrapper     #Cache the gradle
    
android:
    components:
        #- platform-tools
        - build-tools-25.0.0
        #- android-24
        - android-22

        # Additional components
        - extra-google-google_play_services
        - extra-google-m2repository
        - extra-android-m2repository

        #system images
        #- sys-img-armeabi-v7a-android-24
        - sys-img-armeabi-v7a-android-22
  
licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
before_script:
    - chmod +x gradlew      #Grand permissions
    - android list targets
    - echo no | android create avd --force --name test --target android-22 --abi armeabi-v7a    #Create AVD
    - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - ./gradlew check -PdisablePreDex --continue --stacktrace
    - android-wait-for-emulator
    - adb devices   #Display list of devices
    - adb shell input keyevent 82 &
    - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace
    
after_success:
    - ./gradlew jacocoFullReport
    - pip install --user codecov    #Install codecov
    - codecov                       #Run codecov
    
after_failure:      #Upload the crash report to imggur
    - wget http://imgur.com/tools/imgurbash.sh
    - chmod a+x imgurbash.sh
    - adb shell screencap -p | sed 's/\r$//' &gt; screen.png
    - ./imgurbash.sh screen.png
    - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'
